# allow_debugging: off
package_assets: on

javascripts:
  neon: &neon
    - public/javascripts/v4/vendor/neon/neon.js
    - public/javascripts/v4/vendor/neon/stdlib/custom_event.js
    - public/javascripts/v4/vendor/neon/stdlib/custom_event_support.js
    - public/javascripts/v4/vendor/neon/stdlib/node_support.js
    - public/javascripts/v4/vendor/neon/stdlib/bubbling_support.js
    - public/javascripts/v4/vendor/neon/stdlib/widget.js
  defaults: &defaults
    - public/javascripts/include/jquery.1.6.4.js
    - public/javascripts/include/rails.js
    - *neon
    - public/javascripts/include/jquery.placeholder.js
    - public/javascripts/v4/map.js
    - public/javascripts/application.js
    - public/javascripts/v4/DelayedEventEmitter.js
    - public/javascripts/include/smart-resize.js
  jscroll: &jscroll
    - public/javascripts/include/jquery.jscrollpane.min.js
    - public/javascripts/include/jquery.mousewheel.js
    - public/javascripts/include/mwheelIntent.js
  sidebar: &sidebar
    - public/javascripts/cv/dynamicMeasures.js
    - public/javascripts/v4/CVTooltip.js
    - public/javascripts/cv/sidebarToggler.js
    - public/javascripts/cv/accordion.js
    - public/javascripts/cv/slideSection.js
    - public/javascripts/cv/liveFilter.js
    - public/javascripts/cv/jsonForm.js

  home_pack:
    - *defaults
    - *jscroll
    - *sidebar
    - public/javascripts/cv/socialMediaButtons.js
    - public/javascripts/include/highcharts.js
    - public/javascripts/infographics/infoCharts.js
    - public/javascripts/home_init.js
  home_installations_pack:
    - *defaults
    - *jscroll
    - *sidebar
    - public/javascripts/include/jquery.li-scroller.js
    - public/javascripts/home_installations_init.js
  about_pack:
    - *defaults
    - *jscroll
    - *sidebar
    - public/javascripts/cv/socialMediaButtons.js
    - public/javascripts/about_init.js
  mediafeed_pack:
    - *defaults
    - *jscroll
    - *sidebar
    - public/javascripts/include/underscore-min.js
    - public/javascripts/infographics/infoCharts.js
    - public/javascripts/infographics/infoBox.js
    - public/javascripts/infographics/infoTagsTooltip.js
    - public/javascripts/include/jquery.isotope.min.for-posts.js
    - public/javascripts/include/jquery.embedly.min.js
    - public/javascripts/include/moment.min.js
    - public/javascripts/ZeroClipboard.js
    - public/javascripts/include/qunit.js
    - public/javascripts/include/jquery.ba-bbq.min.js
    - public/javascripts/include/jquery.form.js
    - public/javascripts/include/jquery.imgloaded.js
    - public/javascripts/cv/carousel.js
    - public/javascripts/cv/overlay.js
    - public/javascripts/v4/Overlays/OverlaysController.js
    - public/javascripts/v4/Overlays/LinkOverlay.js
    - public/javascripts/v4/Overlays/MediaOverlay.js
    - public/javascripts/v4/Overlays/MediaOverlayCarousel.js
    - public/javascripts/v4/Overlays/MediaOverlayThumbnail.js
    - public/javascripts/cv/video_overlay.js
    - public/javascripts/cv/message.js
    - public/javascripts/v4/MediaTool.js
    - public/javascripts/cv/post.js
    - public/javascripts/cv/filters.js
    - public/javascripts/cv/blogWidget.js
    - public/javascripts/v4/vendor/jquery.mousewheel.js
    - public/javascripts/v4/Loader.js
    - public/javascripts/cv/timeline.js
    - public/javascripts/cv/toggleTweets.js
    - public/javascripts/include/highcharts.js
    - public/javascripts/infographics/infoSidebar.js
    - public/javascripts/cv/socialNavigationIcons.js
    - public/javascripts/mediafeed_init.js
    - public/javascripts/v4/vendor/moment.min.js
    - public/javascripts/v4/vendor/jquery.visible.js
    - public/javascripts/v4/VoicesContainer.js
    - public/javascripts/v4/VoiceElement.js
    - public/javascripts/v4/vendor/fuse.js
    - public/javascripts/v4/MediaFeedSearch.js
  infobox: &infobox
    - public/javascripts/include/jquery.isotope.1.5.19.min.js
    - public/javascripts/include/smart-resize.js
    - public/javascripts/infographics/infoWall.js
    - public/javascripts/infographics/infoCharts.js
    - public/javascripts/infographics/infoBox.js
    - public/javascripts/infographics/infoPane.js
    - public/javascripts/cv/blogWidget.js
  infographics_pack:
    - *defaults
    - *jscroll
    - *sidebar
    - *infobox
    - public/javascripts/ZeroClipboard.js
    - public/javascripts/include/highcharts.js
    - public/javascripts/include/underscore-min.js
    - public/javascripts/cv/socialNavigationIcons.js
    - public/javascripts/infographics/infoWall_init.js
  backstory_pack:
    - *defaults
    - *jscroll
    - *sidebar
    #- public/javascripts/include/jquery-ui.min.js
    #- public/javascripts/include/CSSPlugin.min.js
    #- public/javascripts/include/TweenLite.min.js
    #- public/javascripts/cv/carousel.js
    #- public/javascripts/cv/overlay.js
    - public/javascripts/cv/post.js
    #- public/javascripts/ZeroClipboard.js
    - public/javascripts/cv/blogWidget.js
    #- public/javascripts/backstory/galleryController.js
    #- public/javascripts/backstory/imageWidget.js
    #- public/javascripts/backstory/videoWidget.js
    #- public/javascripts/backstory/paginationWidget.js
    #- public/javascripts/backstory/captionWidget.js
    #- public/javascripts/backstory/timelineWidthController.js
    #- public/javascripts/backstory/dragBar.js
    #- public/javascripts/backstory/timelineSlideController.js
    #- public/javascripts/backstory/detailsViewController.js
    #- public/javascripts/backstory/elementTooltip.js
    #- public/javascripts/backstory/timelineElement.js
    #- public/javascripts/backstory/timelineElementController.js
    #- public/javascripts/backstory/timelineEvent.js
    #- public/javascripts/backstory/timelineEventController.js
    #- public/javascripts/backstory/timelineController.js
    - public/javascripts/cv/socialNavigationIcons.js
    - public/javascripts/v4/Utils.js
    - public/javascripts/v4/Backstory/BackstoryRegistry.js
    - public/javascripts/v4/Backstory/BackstoryController.js
    - public/javascripts/v4/Backstory/BackstoryUIComponent.js
    - public/javascripts/v4/Backstory/BackstoryBreadcrumb.js
    - public/javascripts/v4/Backstory/BackstoryBreadcrumbItem.js
    - public/javascripts/v4/Backstory/BackstoryTimeline.js
    - public/javascripts/v4/Backstory/BackstoryTimelineYear.js
    - public/javascripts/v4/Backstory/BackstoryTimelineMonth.js
    - public/javascripts/v4/Backstory/BackstoryTimelineElement.js
    - public/javascripts/v4/Backstory/BackstoryTimelineCard.js
    - public/javascripts/v4/Backstory/BackstoryGalleryOverlay.js
    - public/javascripts/v4/Backstory/BackstoryGalleryCarrousel.js
    - public/javascripts/v4/Backstory/BackstoryGalleryThumb.js
    - public/javascripts/backstory/backstory_init.js

  admin:
    - public/javascripts/include/jquery.1.6.4.js
    - public/javascripts/include/jquery-ui.min.js
    - public/javascripts/include/rails.js
    - public/javascripts/include/neon.js
    - public/javascripts/include/underscore-min.js
    - public/javascripts/include/jquery.ba-throttle-debounce.min.js
    # - public/javascripts/include/raphael-min.js
    - public/javascripts/include/highcharts.js
    - public/javascripts/include/ajaxfileupload.js
    - public/javascripts/include/jquery.tokeninput.js

    # normal
    - public/javascripts/slider.js
    - public/javascripts/cv/cvmap.js
    - public/javascripts/global.js
    #infobox editor
    - public/javascripts/infographics/infoCharts.js
    - public/javascripts/infographics/infoBox.js
    - public/javascripts/infographics/infoChartDataEditor.js
    - public/javascripts/infographics/infoClipartGallery.js
    - public/javascripts/infographics/infoCustomImage.js
    - public/javascripts/infographics/infoNumber.js
    - public/javascripts/infographics/infoEditor.js
    - public/javascripts/infographics/sortBlocks.js
    - public/javascripts/include/jquery.jscrollpane.min.js
    - public/javascripts/include/jquery.mousewheel.js
    - public/javascripts/include/mwheelIntent.js

  install:
    - public/javascripts/include/jquery.1.6.4.js
    - public/javascripts/include/rails.js
    - public/javascripts/include/neon.js
    - public/javascripts/installForm.js

stylesheets:
  defaults: &defaults
    - public/stylesheets/reset.css
    - public/stylesheets/scaffold.css
    - public/stylesheets/fonts.css
    - public/stylesheets/icon-font.css
    - public/stylesheets/layout.css
    - public/stylesheets/skin.css
    - public/stylesheets/grid.css
    - public/stylesheets/jscrollpane.css
    - public/stylesheets/v4/utilities.css
    - public/stylesheets/v4/buttons.css
    - public/stylesheets/v4/inputs.css
    - public/stylesheets/v4/tooltip.css
    - public/stylesheets/v4/icons.css
    - public/stylesheets/layout/modules/sidebar.css
    - public/stylesheets/skin/modules/sidebar.css
    - public/stylesheets/layout/modules/simple-tooltips.css
    - public/stylesheets/skin/modules/simple-tooltips.css
    - public/stylesheets/layout/modules/voice-headers.css
    - public/stylesheets/skin/modules/voice-headers.css
    - public/stylesheets/v4/tooltips/sidebar-tooltips.css
    - public/stylesheets/v4/tooltips/mediafeed-tweets.css
    - public/stylesheets/v4/tooltips/embeddable-widget.css
    - public/stylesheets/v4/tooltips/media-tools.css
    - public/stylesheets/layout/modules/loaders.css
    - public/stylesheets/skin/modules/loaders.css
    - public/stylesheets/v4/progress.css
  home_pack:
    - *defaults
    - public/stylesheets/layout/modules/notifications.css
    - public/stylesheets/skin/modules/notifications.css
    - public/stylesheets/layout/modules/cover-boxes.css
    - public/stylesheets/skin/modules/cover-boxes.css
  home_installations_pack:
    - *defaults
    - public/stylesheets/layout/modules/notifications.css
    - public/stylesheets/skin/modules/notifications.css
    - public/stylesheets/layout/modules/old-home.css
    - public/stylesheets/skin/modules/old-home.css
  about_pack:
    - *defaults
    - public/stylesheets/layout/modules/tweets-sidebar.css
    - public/stylesheets/skin/modules/tweets-sidebar.css
    - public/stylesheets/layout/modules/about.css
    - public/stylesheets/skin/modules/about.css
  mediafeed_pack:
    - *defaults
    - public/stylesheets/jscrollpane.css
    - public/stylesheets/layout/voices.css
    - public/stylesheets/skin/voices.css
    - public/stylesheets/layout/modules/voice-timeline.css
    - public/stylesheets/skin/modules/voice-timeline.css
    - public/stylesheets/layout/modules/post-boxes.css
    - public/stylesheets/skin/modules/post-boxes.css
    - public/stylesheets/layout/modules/tweets-sidebar.css
    - public/stylesheets/skin/modules/tweets-sidebar.css
    - public/stylesheets/v4/overlays.css
    - public/stylesheets/layout/modules/voice-overlays.css
    - public/stylesheets/skin/modules/voice-overlays.css
    - public/stylesheets/layout/infobox.css
    - public/stylesheets/skin/infobox.css
    - public/javascripts/v4/Loader/Loader.css
    - public/stylesheets/v4/VoiceElement.css
  backstory:
    - *defaults
    - public/stylesheets/v4/backstory/backstory.css
    - public/stylesheets/v4/backstory/backstory-overlay.css
    # - public/stylesheets/skin/backstory.css
    - public/stylesheets/layout/voices.css
    # - public/stylesheets/skin/voices.css
    - public/stylesheets/layout/infobox.css
    # - public/stylesheets/skin/infobox.css
    - public/stylesheets/layout/modules/voice-overlays.css
    - public/stylesheets/skin/modules/voice-overlays.css
    #- public/stylesheets/layout/backstory.css
  infographics:
    - *defaults
    - public/stylesheets/layout/infobox.css
    - public/stylesheets/skin/infobox.css
    - public/stylesheets/layout/modules/voice-overlays.css
    - public/stylesheets/skin/modules/voice-overlays.css
  admin_pack:
    - public/stylesheets/layout/admin.css
    - public/stylesheets/skin/admin.css
    - public/stylesheets/layout/modules/voice-headers.css
    - public/stylesheets/skin/modules/voice-headers.css
    - public/stylesheets/layout/modules/sidebar.css
    - public/stylesheets/skin/modules/sidebar.css
    - public/stylesheets/menubar/WOAHbar.css
  install:
    - 'public/mycrowdvoice/bootstrap.min.css'
    - 'public/mycrowdvoice/bootstrap-responsive.min.css'
    - 'public/mycrowdvoice/install.css'
